{{ HTML::script("http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js") }}
{{ HTML::script("/assets/js/custom.js") }}
{{ HTML::script("/assets/js/selectnav.js") }}
{{ HTML::script("/assets/js/flexslider.js") }}
{{ HTML::script("/assets/js/twitter.js") }}
{{ HTML::script("/assets/js/tooltip.js") }}
{{ HTML::script("/assets/js/effects.js") }}
{{ HTML::script("/assets/js/fancybox.js") }}
{{ HTML::script("/assets/js/carousel.js") }}
{{ HTML::script("/assets/js/isotope.js") }}
{{ HTML::script("/assets/js/jquery-easing-1.3.js") }}
{{ HTML::script("/assets/js/jquery-transit-modified.js") }}
{{ HTML::script("/assets/js/layerslider.transitions.js") }}
{{ HTML::script("/assets/js/layerslider.kreaturamedia.jquery.js") }}
{{ HTML::script("//code.jquery.com/ui/1.11.2/jquery-ui.js") }}
